### PR TITLE
convert to pure python

### PR DESCRIPTION
**Pull request by esheldon**
Remove the C++ code and use calls to math sin/cos

Simplify the setup.py and remove the C and header files

Update the changelog

### CODE REVIEW

**Comment by esheldon** [comment]
Odd, 3.9 fails in CI but works fine on my 3.9 install on ubuntu

**Comment by esheldon** [comment]
I see the tests pass for 3.9 and 3.10 on my ubuntu machine

**Comment by esheldon** [comment]
weird, rerunning the 3.9 test it succeeded

**Comment by esheldon** [comment]
The intermittent failures seem to be related to numpy behavior.  In some of the CI jobs np.sin/cos differed from math.sin/cos

**Review by rmjarvis — APPROVED** [review]
Thanks Erin.  There is a bit more to change on the wheels.yml workflow (since wheels aren't needed anymore), but I can do that.

**Comment by esheldon** [comment]
You're welcome

**Comment by rmjarvis** [comment]
FYI, v1.3.0 is released with this change.  Available on pip now.  Conda should be in a few hours.

**Comment by esheldon** [comment]
got it, thanks

**Pull request merged**
